#ifndef SOURCES_PROJECT_CONF_PROJECT_CONFIG_H_
#define SOURCES_PROJECT_CONF_PROJECT_CONFIG_H_

#define HEARTBEAT_PRIORITY 3
#define SCREEN_UPDATE_PRIORITY 3
#define DS3231M_PRIORITY 2
#define UBLOX_PRIORITY 2
#define BUTTONS_PRIORITY 1
#define FB_SIZE (132 * 64 / 8)
#define LOW_SYSTEM_INTERRUPT_PRIORITY 15
#define USART_INTERRUPT_PRIORITY (LOW_SYSTEM_INTERRUPT_PRIORITY - 1)
#define MAX_UBLOX_MSG_SIZE 100
#define MAX_RX_MSGS	3
#define BUTTON_DEBOUNCE 1 /* 50ms */
#define BUTTON_LONG  40 /* 2000ms */


#endif /* SOURCES_PROJECT_CONF_PROJECT_CONFIG_H_ */
